In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

# 1. Importing Data

In [3]:
df_data = pd.read_csv('creditcard.csv')
# drop the Time attribute which is irrelevatn 
df_data.drop('Time', axis=1, inplace = True)
df_data.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10  ...       V21       V22       V23       V24  \
0  0.098698  0.363787  0.090794  ... -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425 -0.166974  ... -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  0.207643  ...  0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024 -0.054952  ... -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  0.753074  ... -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Amount  Class  
0  0.128539 -0.189115  0.133558 -0.021053  149.62      0  
1  0.167170  0.125895 -0.008983  0.014724    2.69      0  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0  
3  0.647376 -0.221929  0.062723  0.061458  123.50      0  
4 -0.206010  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 30 columns]

# 2. Data Processing and Exploratory Data Analysis (EDA)

In [14]:
case_num = len(df_data)
fraud_num = sum(df_data.Class == 1)
normal_num = sum(df_data.Class == 0)
fraud_proportion = fraud_num/case_num

In [15]:
fraud_proportion

0.001727485630620034

In [16]:
fraud_case = df_data[df_data.Class==1]
normal_case = df_data[df_data.Class==0]

In [17]:
fraud_case.describe()

V1          V2          V3          V4          V5          V6  \
count  492.000000  492.000000  492.000000  492.000000  492.000000  492.000000   
mean    -4.771948    3.623778   -7.033281    4.542029   -3.151225   -1.397737   
std      6.783687    4.291216    7.110937    2.873318    5.372468    1.858124   
min    -30.552380   -8.402154  -31.103685   -1.313275  -22.105532   -6.406267   
25%     -6.036063    1.188226   -8.643489    2.373050   -4.792835   -2.501511   
50%     -2.342497    2.717869   -5.075257    4.177147   -1.522962   -1.424616   
75%     -0.419200    4.971257   -2.276185    6.348729    0.214562   -0.413216   
max      2.132386   22.057729    2.250210   12.114672   11.095089    6.474115   

               V7          V8          V9         V10  ...         V21  \
count  492.000000  492.000000  492.000000  492.000000  ...  492.000000   
mean    -5.568731    0.570636   -2.581123   -5.676883  ...    0.713588   
std      7.206773    6.797831    2.500896    4.897341  ...    3.869304   
min    -43.557242  -41.044261  -13.434066  -24.588262  ...  -22.797604   
25%     -7.965295   -0.195336   -3.872383   -7.756698  ...    0.041787   
50%     -3.034402    0.621508   -2.208768   -4.578825  ...    0.592146   
75%     -0.945954    1.764879   -0.787850   -2.614184  ...    1.244611   
max      5.802537   20.007208    3.353525    4.031435  ...   27.202839   

              V22         V23         V24         V25         V26         V27  \
count  492.000000  492.000000  492.000000  492.000000  492.000000  492.000000   
mean     0.014049   -0.040308   -0.105130    0.041449    0.051648    0.170575   
std      1.494602    1.579642    0.515577    0.797205    0.471679    1.376766   
min     -8.887017  -19.254328   -2.028024   -4.781606   -1.152671   -7.263482   
25%     -0.533764   -0.342175   -0.436809   -0.314348   -0.259416   -0.020025   
50%      0.048434   -0.073135   -0.060795    0.088371    0.004321    0.394926   
75%      0.617474    0.308378    0.285328    0.456515    0.396733    0.826029   
max      8.361985    5.466230    1.091435    2.208209    2.745261    3.052358   

              V28       Amount  Class  
count  492.000000   492.000000  492.0  
mean     0.075667   122.211321    1.0  
std      0.547291   256.683288    0.0  
min     -1.869290     0.000000    1.0  
25%     -0.108868     1.000000    1.0  
50%      0.146344     9.250000    1.0  
75%      0.381152   105.890000    1.0  
max      1.779364  2125.870000    1.0  

[8 rows x 30 columns]

In [18]:
normal_case.describe()

V1             V2             V3             V4  \
count  284315.000000  284315.000000  284315.000000  284315.000000   
mean        0.008258      -0.006271       0.012171      -0.007860   
std         1.929814       1.636146       1.459429       1.399333   
min       -56.407510     -72.715728     -48.325589      -5.683171   
25%        -0.917544      -0.599473      -0.884541      -0.850077   
50%         0.020023       0.064070       0.182158      -0.022405   
75%         1.316218       0.800446       1.028372       0.737624   
max         2.454930      18.902453       9.382558      16.875344   

                  V5             V6             V7             V8  \
count  284315.000000  284315.000000  284315.000000  284315.000000   
mean        0.005453       0.002419       0.009637      -0.000987   
std         1.356952       1.329913       1.178812       1.161283   
min      -113.743307     -26.160506     -31.764946     -73.216718   
25%        -0.689398      -0.766847      -0.551442      -0.208633   
50%        -0.053457      -0.273123       0.041138       0.022041   
75%         0.612181       0.399619       0.571019       0.326200   
max        34.801666      73.301626     120.589494      18.709255   

                  V9            V10  ...            V21            V22  \
count  284315.000000  284315.000000  ...  284315.000000  284315.000000   
mean        0.004467       0.009824  ...      -0.001235      -0.000024   
std         1.089372       1.044204  ...       0.716743       0.723668   
min        -6.290730     -14.741096  ...     -34.830382     -10.933144   
25%        -0.640412      -0.532880  ...      -0.228509      -0.542403   
50%        -0.049964      -0.091872  ...      -0.029821       0.006736   
75%         0.598230       0.455135  ...       0.185626       0.528407   
max        15.594995      23.745136  ...      22.614889      10.503090   

                 V23            V24            V25            V26  \
count  284315.000000  284315.000000  284315.000000  284315.000000   
mean        0.000070       0.000182      -0.000072      -0.000089   
std         0.621541       0.605776       0.520673       0.482241   
min       -44.807735      -2.836627     -10.295397      -2.604551   
25%        -0.161702      -0.354425      -0.317145      -0.327074   
50%        -0.011147       0.041082       0.016417      -0.052227   
75%         0.147522       0.439869       0.350594       0.240671   
max        22.528412       4.584549       7.519589       3.517346   

                 V27            V28         Amount     Class  
count  284315.000000  284315.000000  284315.000000  284315.0  
mean       -0.000295      -0.000131      88.291022       0.0  
std         0.399847       0.329570     250.105092       0.0  
min       -22.565679     -15.430084       0.000000       0.0  
25%        -0.070852      -0.052950       5.650000       0.0  
50%         0.001230       0.011199      22.000000       0.0  
75%         0.090573       0.077962      77.050000       0.0  
max        31.612198      33.847808   25691.160000       0.0  

[8 rows x 30 columns]

Normalize the Amount attribute using the StandardScaler method

In [19]:
from sklearn.preprocessing import StandardScaler

In [22]:
standar_scaler = StandardScaler()
amount = df_data['Amount'].values
df_data['Amount'] = standar_scaler.fit_transform(amount.reshape(-1,1))
df_data.Amount.head()

0    0.244964
1   -0.342475
2    1.160686
3    0.140534
4   -0.073403
Name: Amount, dtype: float64

# 3. Feature Selection and Data Split

In [24]:
X_data = df_data.drop('Class', axis=1)
y_data = df_data.Class.copy()

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
X_train, X_remaining, y_train, y_remaining = train_test_split(X_data, y_data, 
                                                              test_size = 0.2, random_state=314)
X_val, X_test, y_val, y_test = train_test_split(X_remaining, 
                                                y_remaining, test_size=0.5, random_state=314)

# 4. Modeling

## 4-1 Decision Tree

In [27]:
from sklearn.tree import DecisionTreeClassifier

In [36]:
tree_model = DecisionTreeClassifier(max_depth=4, criterion='entropy')
tree_model.fit(X_train, y_train)
tree_pred = tree_model.predict(X_val)

## 4-2 K-Nearest Neighbors

In [28]:
from sklearn.neighbors import KNeighborsClassifier

In [37]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
knn_pred = knn.predict(X_val)

## 4-3 Logistic Regression

In [29]:
from sklearn.linear_model import LogisticRegression

In [46]:
logi = LogisticRegression()
logi.fit(X_train, y_train)
logi_pred = logi.predict(X_val)

In [30]:
from sklearn.svm import SVC

In [40]:
svc = SVC()
svc.fit(X_train, y_train)
svc_pred = svc.predict(X_val)

In [31]:
from sklearn.ensemble import RandomForestClassifier

In [41]:
rf = RandomForestClassifier(max_depth=4)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_val)

In [34]:
from xgboost import XGBClassifier

In [53]:
xgb = XGBClassifier(max_depth=5)
xgb.fit(X_train, y_train)
xgb_pred = xgb.predict(X_val)

# 5. Evaluation

## 5-1 Accuracy score

In [43]:
from sklearn.metrics import accuracy_score

In [44]:
accuracy_score(y_val, tree_pred)

0.9992626663389628

In [45]:
accuracy_score(y_val, knn_pred)

0.9991573329588147

In [47]:
accuracy_score(y_val, logi_pred)

0.9990168884519505

In [48]:
accuracy_score(y_val, svc_pred)

0.9990871107053826

In [49]:
accuracy_score(y_val, rf_pred)

0.9992977774656788

In [54]:
accuracy_score(y_val, xgb_pred)

0.9993679997191109

## 5-2 F1 Score

In [56]:
from sklearn.metrics import f1_score

In [58]:
f1_score(y_val, tree_pred)

0.8372093023255814

In [59]:
f1_score(y_val, knn_pred)

0.7999999999999999

In [60]:
f1_score(y_val, logi_pred)

0.7543859649122807

In [61]:
f1_score(y_val, svc_pred)

0.7758620689655173

In [62]:
f1_score(y_val, rf_pred)

0.8333333333333334

In [63]:
f1_score(y_val, xgb_pred)

0.8548387096774193

## 5-3 Confusion Matrix

In [64]:
from sklearn.metrics import confusion_matrix

In [67]:
confusion_matrix(y_val, tree_pred)

array([[28406,     6],
       [   15,    54]], dtype=int64)

In [68]:
confusion_matrix(y_val, knn_pred)

array([[28409,     3],
       [   21,    48]], dtype=int64)

In [69]:
confusion_matrix(y_val, logi_pred)

array([[28410,     2],
       [   26,    43]], dtype=int64)

In [70]:
confusion_matrix(y_val, svc_pred)

array([[28410,     2],
       [   24,    45]], dtype=int64)

In [71]:
confusion_matrix(y_val, rf_pred)

array([[28411,     1],
       [   19,    50]], dtype=int64)

In [72]:
confusion_matrix(y_val, xgb_pred)

array([[28410,     2],
       [   16,    53]], dtype=int64)